#!/bin/bash
html_files=$(find . -maxdepth 1 -type f -name "*.html") for file in $html_files; do parent_file="../$(basename "$file")" if [ ! -e "$parent_file" ] || [ "$file" -nt "$parent_file" ]; then cp "$file" ".."  echo "Copied $file to parent directory" fi
