#!/usr/bin/env bash
# script for displaying "Best School" 10 times using while loop
# for the 9th iteration, displays Best School and then Hi

i=0
while [ "$i" -lt "10" ]
do
    echo "Best School"

    if [ "$i" -eq "8" ]
    then
        echo "Hi"
    fi

    i=$(( i + 1 ))
done
