#!/usr/bin/env bash
# script for displaying the content of the current directory in list format,
# only the part of the name after the first dash will be displayed

list=$(ls)
for VAR in $list
do
  echo "$VAR" | cut -d "-" -f 2-
done
