#!/usr/bin/env bash
# script for giving information about the school file
# if the file exists print: school file exists
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)
# if the file doesn't exist: school file doesn't exist

file="school"
if [ -e "$file" ]
then
    echo "school file exists"
    if [ ! -s "$file" ]
    then
        echo "school file is empty"
    fi
    if [ -s "$file" ]
    then
        echo "school file is not empty"
    fi
    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
